# Generated by Django 3.2.8 on 2021-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('atas', models.FileField(upload_to='atas')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('avisos', models.FileField(upload_to='avisos')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('outros', models.FileField(upload_to='outros')),
            ],
            options={
                'verbose_name': 'Outro',
                'verbose_name_plural': 'Outros',
            },
        ),
    ]
